# Generated by Django 3.0.7 on 2020-06-09 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0007_auto_20200609_0655'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
